# Ambiente para Programação WEB
# apache + php + mysql + phpmyqdmin
version: "3.8"
services:
    postgres:
        image: httpd
        container_name: 'httpd'
        ports:
            - 8080:80
        volumes:
          - ./htdocs:/usr/local/apache2/htdocs/
        networks:
            - default
networks:
    default:
        driver: bridge